// Code generated by MockGen. DO NOT EDIT.
// Source: client_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=client_interfaces.go -destination=../mock/client_services_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/MKhiriev/go-pass-keeper/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClientCryptoService is a mock of ClientCryptoService interface.
type MockClientCryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockClientCryptoServiceMockRecorder
	isgomock struct{}
}

// MockClientCryptoServiceMockRecorder is the mock recorder for MockClientCryptoService.
type MockClientCryptoServiceMockRecorder struct {
	mock *MockClientCryptoService
}

// NewMockClientCryptoService creates a new mock instance.
func NewMockClientCryptoService(ctrl *gomock.Controller) *MockClientCryptoService {
	mock := &MockClientCryptoService{ctrl: ctrl}
	mock.recorder = &MockClientCryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientCryptoService) EXPECT() *MockClientCryptoServiceMockRecorder {
	return m.recorder
}

// ComputeHash mocks base method.
func (m *MockClientCryptoService) ComputeHash(payload any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeHash", payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeHash indicates an expected call of ComputeHash.
func (mr *MockClientCryptoServiceMockRecorder) ComputeHash(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeHash", reflect.TypeOf((*MockClientCryptoService)(nil).ComputeHash), payload)
}

// DecryptPayload mocks base method.
func (m *MockClientCryptoService) DecryptPayload(cipher models.PrivateDataPayload) (models.DecipheredPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptPayload", cipher)
	ret0, _ := ret[0].(models.DecipheredPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptPayload indicates an expected call of DecryptPayload.
func (mr *MockClientCryptoServiceMockRecorder) DecryptPayload(cipher any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptPayload", reflect.TypeOf((*MockClientCryptoService)(nil).DecryptPayload), cipher)
}

// EncryptPayload mocks base method.
func (m *MockClientCryptoService) EncryptPayload(plain models.DecipheredPayload) (models.PrivateDataPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptPayload", plain)
	ret0, _ := ret[0].(models.PrivateDataPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptPayload indicates an expected call of EncryptPayload.
func (mr *MockClientCryptoServiceMockRecorder) EncryptPayload(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptPayload", reflect.TypeOf((*MockClientCryptoService)(nil).EncryptPayload), plain)
}

// SetEncryptionKey mocks base method.
func (m *MockClientCryptoService) SetEncryptionKey(key []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEncryptionKey", key)
}

// SetEncryptionKey indicates an expected call of SetEncryptionKey.
func (mr *MockClientCryptoServiceMockRecorder) SetEncryptionKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptionKey", reflect.TypeOf((*MockClientCryptoService)(nil).SetEncryptionKey), key)
}

// MockClientAuthService is a mock of ClientAuthService interface.
type MockClientAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockClientAuthServiceMockRecorder
	isgomock struct{}
}

// MockClientAuthServiceMockRecorder is the mock recorder for MockClientAuthService.
type MockClientAuthServiceMockRecorder struct {
	mock *MockClientAuthService
}

// NewMockClientAuthService creates a new mock instance.
func NewMockClientAuthService(ctrl *gomock.Controller) *MockClientAuthService {
	mock := &MockClientAuthService{ctrl: ctrl}
	mock.recorder = &MockClientAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAuthService) EXPECT() *MockClientAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockClientAuthService) Login(ctx context.Context, user models.User) (int64, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockClientAuthServiceMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClientAuthService)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockClientAuthService) Register(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockClientAuthServiceMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockClientAuthService)(nil).Register), ctx, user)
}

// MockClientPrivateDataService is a mock of ClientPrivateDataService interface.
type MockClientPrivateDataService struct {
	ctrl     *gomock.Controller
	recorder *MockClientPrivateDataServiceMockRecorder
	isgomock struct{}
}

// MockClientPrivateDataServiceMockRecorder is the mock recorder for MockClientPrivateDataService.
type MockClientPrivateDataServiceMockRecorder struct {
	mock *MockClientPrivateDataService
}

// NewMockClientPrivateDataService creates a new mock instance.
func NewMockClientPrivateDataService(ctrl *gomock.Controller) *MockClientPrivateDataService {
	mock := &MockClientPrivateDataService{ctrl: ctrl}
	mock.recorder = &MockClientPrivateDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientPrivateDataService) EXPECT() *MockClientPrivateDataServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientPrivateDataService) Create(ctx context.Context, userID int64, plain models.DecipheredPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, plain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClientPrivateDataServiceMockRecorder) Create(ctx, userID, plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientPrivateDataService)(nil).Create), ctx, userID, plain)
}

// Delete mocks base method.
func (m *MockClientPrivateDataService) Delete(ctx context.Context, clientSideID string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, clientSideID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientPrivateDataServiceMockRecorder) Delete(ctx, clientSideID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientPrivateDataService)(nil).Delete), ctx, clientSideID, userID)
}

// Get mocks base method.
func (m *MockClientPrivateDataService) Get(ctx context.Context, clientSideID string, userID int64) (models.DecipheredPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clientSideID, userID)
	ret0, _ := ret[0].(models.DecipheredPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientPrivateDataServiceMockRecorder) Get(ctx, clientSideID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClientPrivateDataService)(nil).Get), ctx, clientSideID, userID)
}

// GetAll mocks base method.
func (m *MockClientPrivateDataService) GetAll(ctx context.Context, userID int64) ([]models.DecipheredPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].([]models.DecipheredPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockClientPrivateDataServiceMockRecorder) GetAll(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockClientPrivateDataService)(nil).GetAll), ctx, userID)
}

// SetEncryptionKey mocks base method.
func (m *MockClientPrivateDataService) SetEncryptionKey(key []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEncryptionKey", key)
}

// SetEncryptionKey indicates an expected call of SetEncryptionKey.
func (mr *MockClientPrivateDataServiceMockRecorder) SetEncryptionKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEncryptionKey", reflect.TypeOf((*MockClientPrivateDataService)(nil).SetEncryptionKey), key)
}

// Update mocks base method.
func (m *MockClientPrivateDataService) Update(ctx context.Context, data models.DecipheredPayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClientPrivateDataServiceMockRecorder) Update(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClientPrivateDataService)(nil).Update), ctx, data)
}

// MockClientSyncService is a mock of ClientSyncService interface.
type MockClientSyncService struct {
	ctrl     *gomock.Controller
	recorder *MockClientSyncServiceMockRecorder
	isgomock struct{}
}

// MockClientSyncServiceMockRecorder is the mock recorder for MockClientSyncService.
type MockClientSyncServiceMockRecorder struct {
	mock *MockClientSyncService
}

// NewMockClientSyncService creates a new mock instance.
func NewMockClientSyncService(ctrl *gomock.Controller) *MockClientSyncService {
	mock := &MockClientSyncService{ctrl: ctrl}
	mock.recorder = &MockClientSyncServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientSyncService) EXPECT() *MockClientSyncServiceMockRecorder {
	return m.recorder
}

// ExecutePlan mocks base method.
func (m *MockClientSyncService) ExecutePlan(ctx context.Context, plan models.SyncPlan, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePlan", ctx, plan, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePlan indicates an expected call of ExecutePlan.
func (mr *MockClientSyncServiceMockRecorder) ExecutePlan(ctx, plan, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePlan", reflect.TypeOf((*MockClientSyncService)(nil).ExecutePlan), ctx, plan, userID)
}

// FullSync mocks base method.
func (m *MockClientSyncService) FullSync(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullSync", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FullSync indicates an expected call of FullSync.
func (mr *MockClientSyncServiceMockRecorder) FullSync(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullSync", reflect.TypeOf((*MockClientSyncService)(nil).FullSync), ctx, userID)
}

// MockClientSyncJob is a mock of ClientSyncJob interface.
type MockClientSyncJob struct {
	ctrl     *gomock.Controller
	recorder *MockClientSyncJobMockRecorder
	isgomock struct{}
}

// MockClientSyncJobMockRecorder is the mock recorder for MockClientSyncJob.
type MockClientSyncJobMockRecorder struct {
	mock *MockClientSyncJob
}

// NewMockClientSyncJob creates a new mock instance.
func NewMockClientSyncJob(ctrl *gomock.Controller) *MockClientSyncJob {
	mock := &MockClientSyncJob{ctrl: ctrl}
	mock.recorder = &MockClientSyncJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientSyncJob) EXPECT() *MockClientSyncJobMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockClientSyncJob) Start(ctx context.Context, userID int64, interval time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx, userID, interval)
}

// Start indicates an expected call of Start.
func (mr *MockClientSyncJobMockRecorder) Start(ctx, userID, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockClientSyncJob)(nil).Start), ctx, userID, interval)
}

// Stop mocks base method.
func (m *MockClientSyncJob) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockClientSyncJobMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockClientSyncJob)(nil).Stop))
}
