// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Rasul Khiriev

// Code generated by MockGen. DO NOT EDIT.
// Source: client_interfaces.go
//
// Generated by this command:
//
//	mockgen -source=client_interfaces.go -destination=../mock/client_store_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/MKhiriev/go-pass-keeper/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLocalPrivateDataRepository is a mock of LocalPrivateDataRepository interface.
type MockLocalPrivateDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLocalPrivateDataRepositoryMockRecorder
	isgomock struct{}
}

// MockLocalPrivateDataRepositoryMockRecorder is the mock recorder for MockLocalPrivateDataRepository.
type MockLocalPrivateDataRepositoryMockRecorder struct {
	mock *MockLocalPrivateDataRepository
}

// NewMockLocalPrivateDataRepository creates a new mock instance.
func NewMockLocalPrivateDataRepository(ctrl *gomock.Controller) *MockLocalPrivateDataRepository {
	mock := &MockLocalPrivateDataRepository{ctrl: ctrl}
	mock.recorder = &MockLocalPrivateDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalPrivateDataRepository) EXPECT() *MockLocalPrivateDataRepositoryMockRecorder {
	return m.recorder
}

// DeletePrivateData mocks base method.
func (m *MockLocalPrivateDataRepository) DeletePrivateData(ctx context.Context, clientSideID string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateData", ctx, clientSideID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateData indicates an expected call of DeletePrivateData.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) DeletePrivateData(ctx, clientSideID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateData", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).DeletePrivateData), ctx, clientSideID, userID)
}

// GetAllPrivateData mocks base method.
func (m *MockLocalPrivateDataRepository) GetAllPrivateData(ctx context.Context, userID int64) ([]models.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPrivateData", ctx, userID)
	ret0, _ := ret[0].([]models.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPrivateData indicates an expected call of GetAllPrivateData.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) GetAllPrivateData(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPrivateData", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).GetAllPrivateData), ctx, userID)
}

// GetAllStates mocks base method.
func (m *MockLocalPrivateDataRepository) GetAllStates(ctx context.Context, userID int64) ([]models.PrivateDataState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStates", ctx, userID)
	ret0, _ := ret[0].([]models.PrivateDataState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStates indicates an expected call of GetAllStates.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) GetAllStates(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStates", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).GetAllStates), ctx, userID)
}

// GetPrivateData mocks base method.
func (m *MockLocalPrivateDataRepository) GetPrivateData(ctx context.Context, clientSideID string, userID int64) (models.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateData", ctx, clientSideID, userID)
	ret0, _ := ret[0].(models.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateData indicates an expected call of GetPrivateData.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) GetPrivateData(ctx, clientSideID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateData", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).GetPrivateData), ctx, clientSideID, userID)
}

// IncrementVersion mocks base method.
func (m *MockLocalPrivateDataRepository) IncrementVersion(ctx context.Context, clientSideID string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementVersion", ctx, clientSideID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementVersion indicates an expected call of IncrementVersion.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) IncrementVersion(ctx, clientSideID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementVersion", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).IncrementVersion), ctx, clientSideID, userID)
}

// SavePrivateData mocks base method.
func (m *MockLocalPrivateDataRepository) SavePrivateData(ctx context.Context, userID int64, data ...models.PrivateData) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userID}
	for _, a := range data {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SavePrivateData", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePrivateData indicates an expected call of SavePrivateData.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) SavePrivateData(ctx, userID any, data ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userID}, data...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePrivateData", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).SavePrivateData), varargs...)
}

// UpdatePrivateData mocks base method.
func (m *MockLocalPrivateDataRepository) UpdatePrivateData(ctx context.Context, data models.PrivateData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePrivateData", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePrivateData indicates an expected call of UpdatePrivateData.
func (mr *MockLocalPrivateDataRepositoryMockRecorder) UpdatePrivateData(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePrivateData", reflect.TypeOf((*MockLocalPrivateDataRepository)(nil).UpdatePrivateData), ctx, data)
}
