// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Rasul Khiriev

// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mock/keychain_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeyChainService is a mock of KeyChainService interface.
type MockKeyChainService struct {
	ctrl     *gomock.Controller
	recorder *MockKeyChainServiceMockRecorder
	isgomock struct{}
}

// MockKeyChainServiceMockRecorder is the mock recorder for MockKeyChainService.
type MockKeyChainServiceMockRecorder struct {
	mock *MockKeyChainService
}

// NewMockKeyChainService creates a new mock instance.
func NewMockKeyChainService(ctrl *gomock.Controller) *MockKeyChainService {
	mock := &MockKeyChainService{ctrl: ctrl}
	mock.recorder = &MockKeyChainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyChainService) EXPECT() *MockKeyChainServiceMockRecorder {
	return m.recorder
}

// DecryptDEK mocks base method.
func (m *MockKeyChainService) DecryptDEK(encryptedDEK, KEK []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptDEK", encryptedDEK, KEK)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptDEK indicates an expected call of DecryptDEK.
func (mr *MockKeyChainServiceMockRecorder) DecryptDEK(encryptedDEK, KEK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptDEK", reflect.TypeOf((*MockKeyChainService)(nil).DecryptDEK), encryptedDEK, KEK)
}

// DecryptData mocks base method.
func (m *MockKeyChainService) DecryptData(encryptedB64 string, DEK []byte, target any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptData", encryptedB64, DEK, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecryptData indicates an expected call of DecryptData.
func (mr *MockKeyChainServiceMockRecorder) DecryptData(encryptedB64, DEK, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptData", reflect.TypeOf((*MockKeyChainService)(nil).DecryptData), encryptedB64, DEK, target)
}

// EncryptData mocks base method.
func (m *MockKeyChainService) EncryptData(data any, DEK []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptData", data, DEK)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptData indicates an expected call of EncryptData.
func (mr *MockKeyChainServiceMockRecorder) EncryptData(data, DEK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptData", reflect.TypeOf((*MockKeyChainService)(nil).EncryptData), data, DEK)
}

// GenerateAuthHash mocks base method.
func (m *MockKeyChainService) GenerateAuthHash(KEK []byte, authSalt string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthHash", KEK, authSalt)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GenerateAuthHash indicates an expected call of GenerateAuthHash.
func (mr *MockKeyChainServiceMockRecorder) GenerateAuthHash(KEK, authSalt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthHash", reflect.TypeOf((*MockKeyChainService)(nil).GenerateAuthHash), KEK, authSalt)
}

// GenerateDEK mocks base method.
func (m *MockKeyChainService) GenerateDEK() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDEK")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateDEK indicates an expected call of GenerateDEK.
func (mr *MockKeyChainServiceMockRecorder) GenerateDEK() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDEK", reflect.TypeOf((*MockKeyChainService)(nil).GenerateDEK))
}

// GenerateEncryptionSalt mocks base method.
func (m *MockKeyChainService) GenerateEncryptionSalt() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateEncryptionSalt")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateEncryptionSalt indicates an expected call of GenerateEncryptionSalt.
func (mr *MockKeyChainServiceMockRecorder) GenerateEncryptionSalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateEncryptionSalt", reflect.TypeOf((*MockKeyChainService)(nil).GenerateEncryptionSalt))
}

// GenerateKEK mocks base method.
func (m *MockKeyChainService) GenerateKEK(masterPassword string, salt []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKEK", masterPassword, salt)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// GenerateKEK indicates an expected call of GenerateKEK.
func (mr *MockKeyChainServiceMockRecorder) GenerateKEK(masterPassword, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKEK", reflect.TypeOf((*MockKeyChainService)(nil).GenerateKEK), masterPassword, salt)
}

// GetEncryptedDEK mocks base method.
func (m *MockKeyChainService) GetEncryptedDEK(DEK, KEK []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEncryptedDEK", DEK, KEK)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEncryptedDEK indicates an expected call of GetEncryptedDEK.
func (mr *MockKeyChainServiceMockRecorder) GetEncryptedDEK(DEK, KEK any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEncryptedDEK", reflect.TypeOf((*MockKeyChainService)(nil).GetEncryptedDEK), DEK, KEK)
}
