// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Rasul Khiriev

// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=../mock/server_adapter_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/MKhiriev/go-pass-keeper/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServerAdapter is a mock of ServerAdapter interface.
type MockServerAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockServerAdapterMockRecorder
	isgomock struct{}
}

// MockServerAdapterMockRecorder is the mock recorder for MockServerAdapter.
type MockServerAdapterMockRecorder struct {
	mock *MockServerAdapter
}

// NewMockServerAdapter creates a new mock instance.
func NewMockServerAdapter(ctrl *gomock.Controller) *MockServerAdapter {
	mock := &MockServerAdapter{ctrl: ctrl}
	mock.recorder = &MockServerAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerAdapter) EXPECT() *MockServerAdapterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServerAdapter) Delete(ctx context.Context, req models.DeleteRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServerAdapterMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServerAdapter)(nil).Delete), ctx, req)
}

// Download mocks base method.
func (m *MockServerAdapter) Download(ctx context.Context, req models.DownloadRequest) ([]models.PrivateData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, req)
	ret0, _ := ret[0].([]models.PrivateData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockServerAdapterMockRecorder) Download(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockServerAdapter)(nil).Download), ctx, req)
}

// GetServerStates mocks base method.
func (m *MockServerAdapter) GetServerStates(ctx context.Context, userID int64) ([]models.PrivateDataState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerStates", ctx, userID)
	ret0, _ := ret[0].([]models.PrivateDataState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerStates indicates an expected call of GetServerStates.
func (mr *MockServerAdapterMockRecorder) GetServerStates(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerStates", reflect.TypeOf((*MockServerAdapter)(nil).GetServerStates), ctx, userID)
}

// Login mocks base method.
func (m *MockServerAdapter) Login(ctx context.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServerAdapterMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockServerAdapter)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockServerAdapter) Register(ctx context.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServerAdapterMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockServerAdapter)(nil).Register), ctx, user)
}

// RequestSalt mocks base method.
func (m *MockServerAdapter) RequestSalt(ctx context.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestSalt", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestSalt indicates an expected call of RequestSalt.
func (mr *MockServerAdapterMockRecorder) RequestSalt(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestSalt", reflect.TypeOf((*MockServerAdapter)(nil).RequestSalt), ctx, user)
}

// SetToken mocks base method.
func (m *MockServerAdapter) SetToken(token string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetToken", token)
}

// SetToken indicates an expected call of SetToken.
func (mr *MockServerAdapterMockRecorder) SetToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetToken", reflect.TypeOf((*MockServerAdapter)(nil).SetToken), token)
}

// Token mocks base method.
func (m *MockServerAdapter) Token() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token.
func (mr *MockServerAdapterMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockServerAdapter)(nil).Token))
}

// Update mocks base method.
func (m *MockServerAdapter) Update(ctx context.Context, req models.UpdateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServerAdapterMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServerAdapter)(nil).Update), ctx, req)
}

// Upload mocks base method.
func (m *MockServerAdapter) Upload(ctx context.Context, req models.UploadRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockServerAdapterMockRecorder) Upload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockServerAdapter)(nil).Upload), ctx, req)
}
