package models

// DecipheredPayload is the client-side plaintext view of a vault item.
//
// It contains decrypted structured representations for all supported data
// types. Exactly one of the type-specific payload fields is expected to be
// populated according to [DataType].
type DecipheredPayload struct {
	// ClientSideID unique identifier generated by the user client.
	ClientSideID string `json:"client_side_id"`

	// UserID is the owner of this private data entry.
	UserID int64 `json:"user_id"`

	// Metadata contains non-sensitive descriptive attributes.
	Metadata Metadata `json:"metadata"`
	// Type indicates which decrypted payload field is populated.
	Type DataType `json:"type"`

	// Type-specific decrypted payload fields.
	LoginData    *LoginData    `json:"login_data,omitempty"`
	LoginURI     *LoginURI     `json:"login_uri,omitempty"`
	TextData     *TextData     `json:"text_data,omitempty"`
	BinaryData   *BinaryData   `json:"binary_data,omitempty"`
	BankCardData *BankCardData `json:"bank_card_data,omitempty"`

	// Notes contains optional decrypted note content.
	Notes *Notes `json:"notes,omitempty"`
	// AdditionalFields contains optional decrypted user-defined fields.
	AdditionalFields *[]CustomField `json:"fields,omitempty"`
}
