package models

import "time"

// PrivateData represents a single vault item.
// It is the primary persistence model for all sensitive user data.
// All confidential payloads are stored encrypted and opaque to the database.
type PrivateData struct {
	// ID is the unique identifier of the record in the database.
	ID int64 `json:"id"`

	// ClientSideID unique identifier generated by the user client.
	ClientSideID string `json:"client_side_id"`

	// UserID is the owner of this private data entry.
	UserID int64 `json:"user_id"`

	// Payload encapsulates all encrypted data fields.
	// This is the part that is hashed and transmitted during updates.
	Payload PrivateDataPayload `json:"payload"`

	// Hash is an integrity checksum derived from the item's content fields:
	// Hash(Metadata, Type, Data, Notes, AdditionalFields).
	// Used to detect changes between client and server versions of the record
	// without comparing the full encrypted payload.
	Hash string `json:"hash"`

	// Version is a monotonic sequence number used for optimistic concurrency control.
	// It is incremented by the server on every successful update.
	// During synchronization, the client sends its local version as 'base_version'.
	// The server rejects the update if the 'base_version' does not match the current
	// version in the database, preventing accidental overwrites of concurrent changes
	// from other devices.
	Version int64 `json:"version"`

	// Deleted field tells if record is deleted
	Deleted bool `json:"deleted"`

	// CreatedAt is the timestamp when the record was created.
	CreatedAt *time.Time `json:"created_at"`

	// UpdatedAt is the timestamp of the last modification.
	UpdatedAt *time.Time `json:"updated_at"`
}

// PrivateDataPayload contains the actual encrypted content and metadata.
// This structure is used for integrity checksum (Hash) calculation
// and represents the "business" part of the record.
type PrivateDataPayload struct {
	// Metadata contains non-sensitive descriptive information
	// such as display name and folder placement.
	// Metadata is stored in DB as an encrypted string.
	Metadata CipheredMetadata `json:"metadata"`

	// Type defines the semantic type of the stored data
	// (e.g. login, secure note, card, binary reference).
	Type DataType `json:"type"`

	// Data holds the encrypted payload.
	// The database treats this field as an opaque string.
	// Data is stored in DB as an encrypted string.
	Data CipheredData `json:"data"`

	// Notes contains optional user notes.
	// Notes may be stored encrypted or in plain form depending on configuration.
	// Notes are stored in DB as an encrypted string.
	Notes *CipheredNotes `json:"notes,omitempty"`

	// AdditionalFields contains optional custom user-defined fields.
	// Each field is independently typed and encrypted.
	// AdditionalFields are stored in DB as an encrypted string.
	AdditionalFields *CipheredCustomFields `json:"fields,omitempty"`
}

// TableName returns the name of the database table
// associated with the PrivateData model.
func (u *PrivateData) TableName() string {
	return "ciphers"
}
