package models

type DecipheredPayload struct {
	// ClientSideID unique identifier generated by the user client.
	ClientSideID string `json:"client_side_id"`

	// UserID is the owner of this private data entry.
	UserID int64 `json:"user_id"`

	Metadata Metadata `json:"metadata"`
	Type     DataType `json:"type"`

	// encrypted data
	LoginData    *LoginData    `json:"login_data,omitempty"`
	LoginURI     *LoginURI     `json:"login_uri,omitempty"`
	TextData     *TextData     `json:"text_data,omitempty"`
	BinaryData   *BinaryData   `json:"binary_data,omitempty"`
	BankCardData *BankCardData `json:"bank_card_data,omitempty"`

	Notes            *Notes         `json:"notes,omitempty"`
	AdditionalFields *[]CustomField `json:"fields,omitempty"`
}
