// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Rasul Khiriev

package models

// UpdateRequest represents a batch partial-update operation for vault items.
//
// Each entry in [PrivateDataUpdates] applies optimistic locking independently
// using its own version value.
type UpdateRequest struct {
	// UserID is the owner of the data to update.
	UserID int64 `json:"user_id"`

	// PrivateDataUpdates is a list of items to update.
	// Each entry carries its own version for independent optimistic locking.
	PrivateDataUpdates []PrivateDataUpdate `json:"private_data_updates"`

	// Hash of serialized PrivateDataUpdates — transport integrity check.
	Hash string `json:"hash"`

	// Length is the total number of entries in PrivateDataUpdates.
	Length int `json:"length"`
}

// PrivateDataUpdate represents criteria for updating a single vault item.
// Only non-nil fields will be updated (partial update support).
type PrivateDataUpdate struct {
	// ClientSideID is the unique identifier generated by the client.
	// Used to correlate server records with local client state.
	ClientSideID string `json:"client_side_id,omitempty"`

	// FieldsUpdate contains the subset of fields to update.
	FieldsUpdate FieldsUpdate `json:"fields_update"`

	// Hash of the full PrivateData record in ciphers table AFTER applying updates — new value for DB.
	// Client computes it from merged state (old unchanged fields + new fields).
	UpdatedRecordHash string `json:"updated_record_hash"`

	// Optimistic locking: must match current DB version, otherwise reject.
	Version int64 `json:"version"`
}

// FieldsUpdate describes optional field-level changes for a single vault item.
// Nil fields are ignored and left unchanged by the update operation.
type FieldsUpdate struct {
	// Metadata contains updated non-sensitive descriptive information.
	// If nil, the field will not be updated.
	Metadata *CipheredMetadata `json:"metadata,omitempty"`

	// Data holds the updated encrypted payload.
	// If nil, the field will not be updated.
	Data *CipheredData `json:"data,omitempty"`

	// Notes contains updated optional user notes.
	// If nil, the field will not be updated.
	Notes *CipheredNotes `json:"notes,omitempty"`

	// AdditionalFields contains updated custom user-defined fields.
	// If nil, the field will not be updated.
	AdditionalFields *CipheredCustomFields `json:"additional_fields,omitempty"`
}
