package models

// DeleteRequest represents criteria for deleting vault items.
// Deletion is implemented as a soft-delete: the record is marked as deleted
// and its version is incremented, but the row is not physically removed.
type DeleteRequest struct {
	// UserID is the owner of the data to delete.
	UserID int64 `json:"user_id"`

	// DeleteEntries is a list of items to delete.
	// Each entry carries its own version for independent optimistic locking.
	DeleteEntries []DeleteEntry `json:"delete_entries"`

	// Length is the total number of entries in DeleteEntries.
	Length int `json:"length"`
}

// DeleteEntry identifies a single vault item to be soft-deleted.
type DeleteEntry struct {
	// ClientSideID is the unique identifier generated by the client.
	// Used to correlate server records with local client state.
	ClientSideID string `json:"client_side_id"`

	// Version is used for optimistic concurrency control.
	// The server will reject the deletion if this value does not match
	// the current version in the database, preventing accidental removal
	// of a record that was concurrently updated by another device.
	Version int64 `json:"version"`
}
