package models

// DownloadRequest represents search criteria for querying vault items.
// Only unencrypted fields can be used for database-level filtering.
type DownloadRequest struct {
	// UserID filters records by owner.
	// Required in most cases to ensure data isolation.
	UserID int64 `json:"user_id"`

	// ClientSideIDs is the array of unique identifiers generated by the client.
	// Used to correlate server records with local client state.
	ClientSideIDs []string `json:"client_side_ids"`

	// Length is the total number of entries in ClientSideIDs.
	Length int `json:"length"`
}
