package models

type UpdateRequest struct {
	// UserID is the owner of the data to delete.
	UserID int64 `json:"user_id"`

	// PrivateDataUpdates is a list of items to update.
	// Each entry carries its own version for independent optimistic locking.
	PrivateDataUpdates []PrivateDataUpdate `json:"private_data_updates"`

	// Hash of serialized PrivateDataUpdates — transport integrity check.
	Hash string `json:"hash"`

	// Length is the total number of entries in PrivateDataUpdates.
	Length int `json:"length"`
}

// PrivateDataUpdate represents criteria for updating a single vault item.
// Only non-nil fields will be updated (partial update support).
type PrivateDataUpdate struct {
	// ClientSideID is the unique identifier generated by the client.
	// Used to correlate server records with local client state.
	ClientSideID string `json:"client_side_id,omitempty"`

	// FieldsUpdate contains a set of fields needed to update
	FieldsUpdate FieldsUpdate `json:"fields_update"`

	// Hash of the full PrivateData record in ciphers table AFTER applying updates — new value for DB.
	// Client computes it from merged state (old unchanged fields + new fields).
	UpdatedRecordHash string `json:"updated_record_hash"`

	// Optimistic locking: must match current DB version, otherwise reject.
	Version int64 `json:"version"`
}

type FieldsUpdate struct {
	// Metadata contains updated non-sensitive descriptive information.
	// If nil, the field will not be updated.
	Metadata *CipheredMetadata `json:"metadata,omitempty"`

	// Data holds the updated encrypted payload.
	// If nil, the field will not be updated.
	Data *CipheredData `json:"data,omitempty"`

	// Notes contains updated optional user notes.
	// If nil, the field will not be updated.
	Notes *CipheredNotes `json:"notes,omitempty"`

	// AdditionalFields contains updated custom user-defined fields.
	// If nil, the field will not be updated.
	AdditionalFields *CipheredCustomFields `json:"additional_fields,omitempty"`
}
