package models

import "time"

// PrivateDataState is a lightweight descriptor of a single vault item.
// It carries just enough information for the client to decide whether
// the local copy is up-to-date, needs to be fetched, pushed, or removed.
// No encrypted payload is included — only identity and change-detection fields.
type PrivateDataState struct {
	// ClientSideID is the unique identifier generated by the client.
	// Used to correlate server records with local client state.
	ClientSideID string `json:"client_side_id"`

	// Hash is an integrity checksum derived from the item's content fields:
	// Hash(Metadata, Type, Data, Notes, AdditionalFields).
	// The client compares this value against its local hash to detect
	// whether the record's payload has diverged.
	Hash string `json:"hash"`

	// Version is a monotonic sequence number incremented by the server
	// on every successful write. The client uses it for optimistic
	// concurrency control when pushing local changes.
	Version int64 `json:"version"`

	// Deleted indicates that the record has been soft-deleted.
	// The client should remove (or hide) the corresponding local entry
	// and stop sending it in future sync requests.
	Deleted bool `json:"deleted"`

	// UpdatedAt is the timestamp of the last server-side modification.
	// Can be used by the client for display purposes or conflict
	// resolution heuristics (e.g. last-write-wins).
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// SyncPlan is the result of comparing server and client PrivateDataState slices.
// Each field contains items that require a specific sync operation.
// All fields are nil by default — a nil slice means no action needed for that category.
type SyncPlan struct {
	// Download contains items that must be fetched from the server to the client.
	// Covers two sub-cases:
	//   - new records that exist only on the server;
	//   - existing records where the server version is ahead of the client.
	Download []PrivateDataState

	// Upload contains new items that exist only on the client
	// and have never been pushed to the server.
	Upload []PrivateDataState

	// Update contains items where the client holds a newer or diverged version
	// that must be written back to the server.
	// Covers two sub-cases:
	//   - same version but hash mismatch (local edit not yet pushed);
	//   - client version is ahead of the server (offline edits).
	Update []PrivateDataState

	// DeleteClient contains items that must be removed from the client.
	// The server holds a newer version that is soft-deleted (Deleted == true).
	DeleteClient []PrivateDataState

	// DeleteServer contains items that must be removed from the server.
	// The client holds a newer or equal version that is soft-deleted (Deleted == true).
	DeleteServer []PrivateDataState
}
