package models

import "time"

// User represents an account entity used for authentication and authorization.
// It contains identity attributes and credential-related data.
// Sensitive fields must never be exposed outside trusted boundaries.
type User struct {
	// UserID is the internal unique identifier of the user.
	// It is not exposed via JSON and is used only at the persistence layer.
	UserID int64 `json:"user_id"`

	// Login is the unique user login identifier.
	// Typically used during authentication.
	Login string `json:"login"`

	// Name is the display name of the user.
	// It is non-sensitive and may be shown in UI.
	Name string `json:"name"`

	// MasterPassword used only to hold data inside a client login process
	// Never send it.
	MasterPassword string `json:"-"`

	// AuthHash is the client-side derived hash of the master password.
	// The server uses it ONLY to verify identity during login.
	// It is never used for encryption or key derivation on the server side.
	// Never store plaintext password here.
	AuthHash string `json:"auth_hash"`

	// EncryptionSalt is a random value generated by the client during registration.
	// It is NOT secret and is returned to the client before login so they can
	// recompute KEK = KDF(password, salt) and AuthHash on their side.
	EncryptionSalt string `json:"encryption_salt"`

	// EncryptedMasterKey is the DEK (Data Encryption Key) wrapped by the KEK.
	// KEK is derived from the user's password and never stored on the server.
	// This field is returned to the client after successful authentication
	// so the client can unwrap it using their KEK and access their data.
	// The server cannot decrypt this value without the user's password.
	EncryptedMasterKey string `json:"encrypted_master_key"`

	// MasterPasswordHint is an optional user-provided hint.
	// It is never exposed via JSON and must not contain sensitive data.
	MasterPasswordHint string `json:"-"`

	// CreatedAt is the timestamp when the user account was created.
	// Used for auditing and lifecycle management.
	CreatedAt time.Time `json:"created_at"`
}

// TableName returns the name of the database table
// associated with the User model.
func (u User) TableName() string {
	return "users"
}
